title: Aramayis Mirzoyan
description: Full-Stack Developer
url: "https://aramayismirzoyan.com"
plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
  posts:
    output: true

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: /blog/:title/